name: if demo
on:
  push:
jobs:
  id-demo:
    runs-on: ubuntu-latest

    steps:
     - name: Run if branch main
       if: github.ref == 'refs/heads/main'
       run: echo "Running for main branch"

     - name: Run if branch main - 2
       if: github.ref_name == 'main'
       run:  echo "this is the another way to define if confition same output"
       
